---
# tasks file for docker
- name: Install pip
  yum: name=python-pip state=present

- name: uninstall docker py
  shell: pip uninstall docker-py

- name: install pyOpenSSL
  shell: pip install --ignore-installed pyOpenSSL

- name: install twillo
  shell: pip install twilio

- name: install docker-py
  shell: pip install docker
  pip: name=docker-py

- name: copy All files of Project
  copy:
    src: /home/ec2-user/Blogs
    dest: /home/ec2-user/

- name: copy All files of File
  copy:
    src: /home/ec2-user/Blogs/docker
    dest: /home/ec2-user/Blogs

- name: check files
  shell: ls -a /home/ec2-user/Blogs

- name: Build Docker image from Dockerfile
  docker_image:
    name: web
    path: /home/ec2-user/Blogs/
    state: present

- name: Running the container
  docker_container:
    image: web:latest
    name: web
    state: started
    ports:
      - "8080"
    
- name: Check if container is running
  shell: docker ps
